server.port=8083

spring.application.name=api-gateway

spring.cloud.gateway.server.webmvc.routes[0].id=appointment-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://appointment-service:8080
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/appointments/**

spring.cloud.gateway.server.webmvc.routes[1].id=request-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://request-service:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/requests/**

spring.cloud.gateway.server.webmvc.routes[2].id=user-service
spring.cloud.gateway.server.webmvc.routes[2].uri=http://user-service:8081
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/users/**

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins[0]=http://127.0.0.1:5501
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedOrigins[1]=http://localhost:5501

spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods[0]=GET
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods[1]=POST
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods[2]=PUT
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods[3]=PATCH
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods[4]=DELETE
spring.cloud.gateway.globalcors.cors-configurations[/**].allowedMethods[5]=OPTIONS

spring.cloud.gateway.globalcors.cors-configurations[/**].allowedHeaders[0]=*
spring.cloud.gateway.globalcors.cors-configurations[/**].allowCredentials=false